### ISSUE TITLE
Fix typo on Readme

### ISSUE THREAD

**Issue by jomefavourite** [zero-to-mastery/file-io#43]
Bdlow should be below
![image](https://github.com/zero-to-mastery/file-io/assets/54733225/fdf70fe6-5087-48e4-adbf-3c2fe2aae63a)

Please assign to me

**Comment by l-white** [comment]
Fixed -- thank you. Please feel free to follow the guidelines to contribute to Hacktoberfest. In the future, you can submit a pull request with a change.

**Comment by jomefavourite** [comment]
> he future, you can submit a pull

Alright
